name: Deploy TDS Virtual TA

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test API endpoints
      run: |
        python -m pytest tests/ -v || echo "Tests not found, skipping"
    
    - name: Start application
      run: |
        python app.py &
        sleep 10
        
    - name: Test API health
      run: |
        curl -f http://localhost:8000/health || exit 1
        
    - name: Test API endpoint
      run: |
        curl -f -X POST http://localhost:8000/api/ \
          -H "Content-Type: application/json" \
          -d '{"question": "What is TDS?"}' || exit 1

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to production
      run: |
        echo "Add your deployment steps here"
        echo "Examples:"
        echo "- Deploy to Heroku"
        echo "- Deploy to Railway"
        echo "- Deploy to Render"
        echo "- Deploy to Google Cloud Run"
